columnSuffix: null
handle: artikelContentJuist
instructions: null
name: 'artikel content juist'
searchable: false
settings:
  availableTransforms: ''
  availableVolumes: '*'
  configSelectionMode: choose
  defaultTransform: ''
  manualConfig: ''
  purifierConfig: null
  purifyHtml: true
  removeEmptyTags: false
  removeInlineStyles: false
  removeNbsp: false
  tinymceConfig: null
translationKeyFormat: null
translationMethod: none
type: spicyweb\tinymce\fields\TinyMCE
