color: null
fieldLayouts:
  b4f3656a-cad7-4537-a59b-545acadbc1c1:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-08-19T18:43:12+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: a17d96ba-4e4b-4317-9eb6-25e992dcf718
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-19T18:44:37+00:00'
            elementCondition: null
            fieldUid: aca73f93-ee27-4646-8d4f-4ac17e2ac440 # foto
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fae07936-3095-4af5-add6-1048dd2a71ed
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-19T18:44:37+00:00'
            elementCondition: null
            fieldUid: 2c8f1234-07c8-4262-baa9-5d2d971870a0 # header artikels
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fb576e36-6bc2-4660-9919-f6746fd3526b
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-19T18:44:37+00:00'
            elementCondition: null
            fieldUid: 8435d9ed-8c6d-480c-9880-338bbef57700 # Ondertekst
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 16d955a1-a952-419f-95f3-58108d6cfa82
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-19T18:44:37+00:00'
            elementCondition: null
            fieldUid: 5e6ea322-3552-4d3a-bebd-c4071ff51416 # datum
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ef1fcf48-01e3-4ab3-8d53-59e17d36cfc5
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-19T18:44:37+00:00'
            elementCondition: null
            fieldUid: 57eae1ce-7a63-4f46-8679-22d180b96c37 # unlike
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e23ab59f-2679-4002-b656-d60bc7bf99c3
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-21T09:04:40+00:00'
            elementCondition: null
            fieldUid: c3540767-a9af-489b-9286-387fa8734e2a # like
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 79298bb4-acd9-489b-a3fe-fe4b5d865a0e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-21T09:37:13+00:00'
            elementCondition: null
            fieldUid: 40f7c704-a6ea-41b4-8d96-dd710ae9e870 # hoofd foto artikel
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cc9b6c5a-8f25-431f-b509-1d9a7aafbd3c
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-21T10:43:32+00:00'
            elementCondition: null
            fieldUid: d632224b-b301-497d-b11e-558c7a994bf0 # artikel categorie
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 88145df3-9ecf-440a-a396-b73f7ff0235c
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-21T10:15:23+00:00'
            elementCondition: null
            fieldUid: 74eda977-9b23-42f2-b723-3f6aa765ee0c # titel artikel
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4b86f1be-9815-4a9a-9c37-3c01c028dd05
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-21T10:27:47+00:00'
            elementCondition: null
            fieldUid: 2fb395ff-8e5f-42c7-8a9f-bf821b057690 # juiste feiten tekst
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ea4d014d-4c1d-472a-b146-4e343dda62b5
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-21T10:33:33+00:00'
            elementCondition: null
            fieldUid: a08b29a6-c37b-4620-abf5-1aa612dee1dc # bewering1 titel
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4970c1b6-4667-4db4-8595-01c5f58cacb8
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-21T10:33:33+00:00'
            elementCondition: null
            fieldUid: e9597db3-8e0b-4d00-815b-4978d310ebde # bewerking2 titel
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c93b73ec-6a4b-4b09-aa9a-916bfa6838d6
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-21T10:33:33+00:00'
            elementCondition: null
            fieldUid: e50cc673-9c06-4b69-90dc-9b2e7b6c70a7 # bewerking1 bron
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 23261146-c48f-4627-a39a-3c819054da3d
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-21T10:33:33+00:00'
            elementCondition: null
            fieldUid: 5832ec44-2ba7-4173-b102-208ad9276fbc # bewerking2 bron
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d98d9ee3-3830-4ee2-ac25-08663e0e52ff
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-21T10:33:33+00:00'
            elementCondition: null
            fieldUid: 6ab0fbfc-4fb9-47da-aed9-c57efb665ec3 # bewering1 uitleg
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 67ffbb02-5f14-4af9-ad27-f2686397aee9
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-21T10:33:33+00:00'
            elementCondition: null
            fieldUid: c0ffe190-38c9-4604-951c-828963f50f4e # bewerking2 uitleg
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 347faaf7-085d-4a37-a476-3e3c65cec01a
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-21T12:02:42+00:00'
            elementCondition: null
            fieldUid: 5d10a239-715c-4442-b38e-7bbe699e9fea # artikel content
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3ac86850-1d48-4ba4-aae1-25be013ef4a5
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 5a624fc2-bc28-4da9-86d1-d3def142b77b
        userCondition: null
handle: artikelsPolitiek
hasTitleField: true
icon: ''
name: 'artikels politiek'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
