color: null
fieldLayouts:
  7e842b7f-cfed-49f2-86dc-63a735b90820:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-08-19T18:20:46+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: e935be1d-7eb4-4247-865a-cac80192cc59
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-19T18:22:02+00:00'
            elementCondition: null
            fieldUid: aca73f93-ee27-4646-8d4f-4ac17e2ac440 # foto
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f28d1f19-3318-4799-a057-38476579377f
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-19T18:22:02+00:00'
            elementCondition: null
            fieldUid: 2c8f1234-07c8-4262-baa9-5d2d971870a0 # header artikels
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 84056610-8d3f-4477-bcd1-0563e9b1bdf5
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-19T18:22:02+00:00'
            elementCondition: null
            fieldUid: 8435d9ed-8c6d-480c-9880-338bbef57700 # Ondertekst
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6b4b713d-660e-4c92-947c-465285c49596
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-19T18:32:28+00:00'
            elementCondition: null
            fieldUid: 5e6ea322-3552-4d3a-bebd-c4071ff51416 # datum
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e05736cd-e6a4-4ba1-916a-eb1ddd2c71e8
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-19T18:27:22+00:00'
            elementCondition: null
            fieldUid: 57eae1ce-7a63-4f46-8679-22d180b96c37 # like
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e837a4c1-5994-4f10-9518-968cbad00912
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: d9abbfc6-e1bc-4947-8510-ea3957148479
        userCondition: null
handle: artikelsnieuw
hasTitleField: true
icon: ''
name: 'artikels nieuw'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
