color: green
fieldLayouts:
  78965732-1bc3-472a-81bd-8a73ba67e32f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-08-19T17:39:12+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 9d8470ae-2eb6-4c21-9687-85a98262351e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-19T17:40:53+00:00'
            elementCondition: null
            fieldUid: 2c8f1234-07c8-4262-baa9-5d2d971870a0 # header artikels
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1368ae47-337a-4a38-b7d8-153bdf86817d
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-19T18:08:28+00:00'
            elementCondition: null
            fieldUid: aca73f93-ee27-4646-8d4f-4ac17e2ac440 # foto
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fd9b8e08-3bcd-4f6a-8ae0-ff7d8a47027e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-19T17:52:15+00:00'
            elementCondition: null
            fieldUid: 8435d9ed-8c6d-480c-9880-338bbef57700 # Ondertekst
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1881bc6e-38b1-42e4-a177-a50b18acc262
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-19T17:55:08+00:00'
            elementCondition: null
            fieldUid: 5e6ea322-3552-4d3a-bebd-c4071ff51416 # datum
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7d9156bd-f300-4d83-a136-bbad00eae8d2
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 4a710a3d-7be5-4c1c-b84f-17967c120a82
        userCondition: null
handle: carouselDefault
hasTitleField: true
icon: ''
name: 'carousel default'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
