color: green
fieldLayouts:
  78965732-1bc3-472a-81bd-8a73ba67e32f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-08-19T17:39:12+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 9d8470ae-2eb6-4c21-9687-85a98262351e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-19T17:40:53+00:00'
            elementCondition: null
            fieldUid: 2c8f1234-07c8-4262-baa9-5d2d971870a0 # header artikels
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1368ae47-337a-4a38-b7d8-153bdf86817d
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-19T18:08:28+00:00'
            elementCondition: null
            fieldUid: aca73f93-ee27-4646-8d4f-4ac17e2ac440 # foto
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fd9b8e08-3bcd-4f6a-8ae0-ff7d8a47027e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-19T17:52:15+00:00'
            elementCondition: null
            fieldUid: 8435d9ed-8c6d-480c-9880-338bbef57700 # Ondertekst
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1881bc6e-38b1-42e4-a177-a50b18acc262
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-19T17:55:08+00:00'
            elementCondition: null
            fieldUid: 5e6ea322-3552-4d3a-bebd-c4071ff51416 # datum
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7d9156bd-f300-4d83-a136-bbad00eae8d2
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-21T09:37:32+00:00'
            elementCondition: null
            fieldUid: 40f7c704-a6ea-41b4-8d96-dd710ae9e870 # hoofd foto artikel
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d9fa626b-36fb-4a2b-95a4-382468e51870
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-21T10:43:38+00:00'
            elementCondition: null
            fieldUid: d632224b-b301-497d-b11e-558c7a994bf0 # artikel categorie
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dcc431f1-6cdb-472e-8c6c-d12919855099
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-21T10:16:16+00:00'
            elementCondition: null
            fieldUid: 74eda977-9b23-42f2-b723-3f6aa765ee0c # titel artikel
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a8b953ba-3c82-483c-bee3-1d664f4472ff
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-21T10:27:56+00:00'
            elementCondition: null
            fieldUid: 2fb395ff-8e5f-42c7-8a9f-bf821b057690 # juiste feiten tekst
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7106d097-e36b-4685-ad44-4d57c940e573
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-21T10:32:08+00:00'
            elementCondition: null
            fieldUid: a08b29a6-c37b-4620-abf5-1aa612dee1dc # bewering1 titel
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c1c3a26f-abd0-4ac4-8e78-7186594b09c1
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-21T10:32:08+00:00'
            elementCondition: null
            fieldUid: e9597db3-8e0b-4d00-815b-4978d310ebde # bewerking2 titel
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9b4b6779-478e-4947-b1b8-101de01916ce
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-21T10:32:08+00:00'
            elementCondition: null
            fieldUid: e50cc673-9c06-4b69-90dc-9b2e7b6c70a7 # bewerking1 bron
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 107f9339-d237-4c73-99cf-2c6380b684a8
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-21T10:32:08+00:00'
            elementCondition: null
            fieldUid: 5832ec44-2ba7-4173-b102-208ad9276fbc # bewerking2 bron
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7a38b45e-30dd-46d4-a941-af1877b47141
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-21T10:32:08+00:00'
            elementCondition: null
            fieldUid: 6ab0fbfc-4fb9-47da-aed9-c57efb665ec3 # bewering1 uitleg
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 08b4cee7-1725-4b34-9838-199496a36b64
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-21T10:32:08+00:00'
            elementCondition: null
            fieldUid: c0ffe190-38c9-4604-951c-828963f50f4e # bewerking2 uitleg
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2349481e-7470-49dd-81ba-739b5e092d39
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 4a710a3d-7be5-4c1c-b84f-17967c120a82
        userCondition: null
handle: carouselDefault
hasTitleField: true
icon: ''
name: 'carousel default'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
