color: null
fieldLayouts:
  24039ccc-27a4-4640-aa3b-fc40e8852509:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-08-21T13:13:05+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: d0372936-dcb3-4fa2-aea6-0308b488a346
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-21T13:14:18+00:00'
            elementCondition: null
            fieldUid: fa58d604-e2d4-4f50-89ee-1da0ca242425 # facebook
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6a602f6d-cf38-4222-b6a4-889928d262f4
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 2a2de423-f0dd-4acb-b3be-51e5e65316f9
        userCondition: null
handle: facebook
hasTitleField: true
icon: ''
name: facebook
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
