color: null
fieldLayouts:
  62d9352e-ea1f-488a-948a-49d5da3f8bcb:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-08-21T13:13:20+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: c1f8566a-5253-443e-b09c-5aea3788d33d
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-21T13:14:27+00:00'
            elementCondition: null
            fieldUid: 290b1cae-86b6-4b56-8610-9c213df8fcb6 # google
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4e48866a-245a-4926-acbe-cb0862efe959
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 490f9b09-c871-4111-9a2a-104b9b632bdd
        userCondition: null
handle: google
hasTitleField: true
icon: ''
name: google
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
