color: null
fieldLayouts:
  949f4579-7b74-41bf-a235-798a759d25d5:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-08-20T15:36:21+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: f8ae6988-993b-4f94-bc60-27bf9f238904
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-20T15:39:12+00:00'
            elementCondition: null
            fieldUid: 9bae6ee1-9bcc-4085-a536-e952a459f30e # title home
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b4a8cbc1-1276-4721-8843-dd7e3822888f
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 33f6fbdc-f91a-4c04-99a0-b32973d575f5
        userCondition: null
handle: headerHome
hasTitleField: true
icon: ''
name: 'header home'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
