color: null
fieldLayouts:
  b7e7c24b-923a-4c81-8ff3-2c816510f2de:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-08-21T13:21:30+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 691f198f-b3b9-4d2b-9dcf-6c21a2c8bb40
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-21T13:22:51+00:00'
            elementCondition: null
            fieldUid: c8270adb-098d-4979-9f74-9b64381ba1ae # patroon
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e5aa7991-e005-4779-b06b-9c6aad90bc0d
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 74d5bd08-d28f-4755-a64e-df9a7f32d762
        userCondition: null
handle: patroon
hasTitleField: true
icon: ''
name: patroon
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
