altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  f3637f46-40c1-4b67-8f5c-ae9da73f75f1:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-08-21T13:14:26+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: ca81ab42-5d55-40c6-847e-fb713efd4d60
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 251aa2df-5265-4cb2-a3f3-bd3ea1208d28
        userCondition: null
fs: google
handle: google
name: google
sortOrder: 7
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: google
transformSubpath: ''
