altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  c27ccb9c-92be-455e-b651-9a0ca5784255:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-08-21T08:54:26+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: abdca883-22b0-4489-b7ad-20905570eb87
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-21T08:55:44+00:00'
            elementCondition: null
            fieldUid: c3540767-a9af-489b-9286-387fa8734e2a # like
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 61254514-7368-4ee3-a3c3-787804a70236
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: da6f3d1a-7255-4e6c-9df8-bf029067cd62
        userCondition: null
fs: likeButton
handle: like
name: like
sortOrder: 3
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: likeButton
transformSubpath: ''
