altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  5a8dd048-3db0-437d-9167-8f0b22ffeb81:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-08-21T13:20:52+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 78fa2039-656f-436e-ab1f-df51a6442b67
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 7aa21774-ef5e-4688-bd27-9503b87f55fe
        userCondition: null
fs: patroon
handle: patroon
name: patroon
sortOrder: 8
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: patroon
transformSubpath: ''
