altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  aebf0503-23f8-410a-a734-1b95a1ee7114:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-08-21T13:46:35+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 8e53ebce-946b-4359-b215-3e726bb801ad
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 66d22514-bc46-4276-890d-ed4b998b35aa
        userCondition: null
fs: profielfoto
handle: profielfoto
name: profielfoto
sortOrder: 9
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: profielfoto
transformSubpath: ''
