dateModified: 1724086126
email:
  fromEmail: isa.haes@hotmail.com
  fromName: 2Check
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    6ce5199d-3c4c-465d-81f1-7d9cc92c7cb5: 2Check # 2Check
    72bbff78-21f3-4733-a195-230c2740ee45: 2Check # 2Check
system:
  edition: solo
  live: true
  name: 2Check
  schemaVersion: 5.3.0.2
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
