dateModified: 1724321887
email:
  fromEmail: isa.haes@hotmail.com
  fromName: 2Check
  transportType: craft\mail\transportadapters\Sendmail
fs:
  facebook:
    hasUrls: true
    name: facebook
    settings:
      path: '@webroot'
    type: craft\fs\Local
    url: '@web'
  fotoArtikels:
    hasUrls: true
    name: foto_artikels
    settings:
      path: '@webroot'
    type: craft\fs\Local
    url: '@web'
  google:
    hasUrls: true
    name: google
    settings:
      path: '@webroot'
    type: craft\fs\Local
    url: '@web'
  hoofdFotoArtikels:
    hasUrls: true
    name: 'hoofd foto artikels'
    settings:
      path: '@webroot'
    type: craft\fs\Local
    url: '@web'
  likeButton:
    hasUrls: true
    name: 'like button'
    settings:
      path: '@webroot'
    type: craft\fs\Local
    url: '@web'
  logo:
    hasUrls: true
    name: logo
    settings:
      path: '@webroot'
    type: craft\fs\Local
    url: '@web'
  patroon:
    hasUrls: true
    name: patroon
    settings:
      path: '@webroot'
    type: craft\fs\Local
    url: '@web'
  profielfoto:
    hasUrls: true
    name: profielfoto
    settings:
      path: '@webroot'
    type: craft\fs\Local
    url: '@web'
  unlikeButton:
    hasUrls: true
    name: 'unlike button'
    settings:
      path: '@webroot'
    type: craft\fs\Local
    url: '@web'
meta:
  __names__:
    1cdd2ea4-0d92-4af7-b3b6-e014fca37949: logo # logo
    2c8f1234-07c8-4262-baa9-5d2d971870a0: 'header artikels' # header artikels
    2cdd72bc-1d38-4925-b04d-71748ae3ed3c: 'zoeken artikels' # zoeken artikels
    02d6d5d6-24c9-43f0-ac60-880b4f29cdf7: carousel # carousel
    2fb395ff-8e5f-42c7-8a9f-bf821b057690: 'juiste feiten tekst' # juiste feiten tekst
    3b0729a9-8590-481e-a903-18bc9937e58c: facebook # facebook
    3f62a56f-6793-4e2d-b5f8-c9ed9e391cb9: 'current url' # current url
    4c619518-4eda-4616-83af-c7c45bd57fc1: like # like
    4cbf1e6b-1fdc-4d86-93fe-8d42307ae831: google # google
    4ff99ef7-44b8-40c2-ae5e-5ffe49547c5e: 'Public Schema' # Public Schema
    5b3d35e2-3e3a-4c1e-aea4-7117f0a6e75f: 'foto artikels' # foto artikels
    5d01fce5-c081-46fe-9d61-6891b63888aa: logo # logo
    5e6ea322-3552-4d3a-bebd-c4071ff51416: datum # datum
    6a29b368-5d9f-4bc6-bad9-8ddfd5598443: 'nieuw artikels' # nieuw artikels
    6ab0fbfc-4fb9-47da-aed9-c57efb665ec3: 'bewering1 uitleg' # bewering1 uitleg
    6ce5199d-3c4c-465d-81f1-7d9cc92c7cb5: 2Check # 2Check
    6cee1da6-efd9-49b5-a1a0-c64cbd2823a3: profielfoto # profielfoto
    7b7e2a12-db70-497e-b18a-a7c30c5091a2: 'carousel default' # carousel default
    8f3c7b4d-35c5-44d6-82ea-8078c61b9648: 'gezondheid artikels' # gezondheid artikels
    8f804de6-dd92-46e8-b249-be52447a4040: patroon # patroon
    9bae6ee1-9bcc-4085-a536-e952a459f30e: 'title home' # title home
    9bd313e9-1842-4821-8e26-a7db5c405e78: unlike # unlike
    12d8ad5e-decf-446a-ba4a-7c92800df418: logo # logo
    40f7c704-a6ea-41b4-8d96-dd710ae9e870: 'hoofd foto artikel' # hoofd foto artikel
    049d17ed-0f14-46ff-b095-a6c37a16a6d1: google # google
    57eae1ce-7a63-4f46-8679-22d180b96c37: unlike # unlike
    60c513b9-5d4d-4b46-bea2-e99c8c10c220: profielfoto # profielfoto
    72bbff78-21f3-4733-a195-230c2740ee45: 2Check # 2Check
    74eda977-9b23-42f2-b723-3f6aa765ee0c: 'titel artikel' # titel artikel
    261df0be-e42b-41da-8dd5-9898c693811e: facebook # facebook
    290b1cae-86b6-4b56-8610-9c213df8fcb6: google # google
    416fb60b-f4a2-4850-907b-d6d6d485efb2: logo # logo
    5832ec44-2ba7-4173-b102-208ad9276fbc: 'bewerking2 bron' # bewerking2 bron
    6264eed4-2b98-4673-9d76-0bf0766e2a70: google # google
    8435d9ed-8c6d-480c-9880-338bbef57700: Ondertekst # Ondertekst
    8806ec29-7040-4c68-b837-653a97b1b53f: 'header home' # header home
    14327aad-e9d5-4b95-b024-a531ee6ef91d: 'politiek artikels' # politiek artikels
    69212d03-788a-48a7-bdb8-2359e675b493: 'hoofd foto artikel' # hoofd foto artikel
    953405b4-0756-4515-9553-38073cb87d35: 'artikels nieuw' # artikels nieuw
    a08b29a6-c37b-4620-abf5-1aa612dee1dc: 'bewering1 titel' # bewering1 titel
    a1e0a4fe-f683-49a0-9124-e57043a352ce: facebook # facebook
    a6dc8106-631a-4f64-92ba-ed7c809e459b: 'header home' # header home
    a8e7c616-9c15-41d5-a729-95e1bbbca35d: patroon # patroon
    a98c0992-0d12-4610-b20f-d26dc4bbc2a6: categories # categories
    ac064d3d-58bb-4e5a-acc4-ef5b3ee70329: 'artikels zoeken' # artikels zoeken
    aca73f93-ee27-4646-8d4f-4ac17e2ac440: foto # foto
    af5b90f4-180a-44b4-8b01-aa518a66f395: 'artikels politiek' # artikels politiek
    b7ff6b30-2938-4468-b7a2-adc695db9827: meldingen # meldingen
    c0ffe190-38c9-4604-951c-828963f50f4e: 'bewerking2 uitleg' # bewerking2 uitleg
    c896b617-75ac-4296-a987-306fd0f94e92: 'meldingen foto' # meldingen foto
    c1766d49-d9d6-45d2-b183-e17d3a217c0d: 'economie artikels' # economie artikels
    c8270adb-098d-4979-9f74-9b64381ba1ae: patroon # patroon
    c3540767-a9af-489b-9286-387fa8734e2a: like # like
    cbf792d9-1fbd-4b6c-9a61-75e1c9cf97f5: profielfoto # profielfoto
    ce57863f-4d62-4ddc-b803-6497a2a1747a: profielfoto # profielfoto
    d461b1d1-fd86-4c26-889f-b62182b73714: patroon # patroon
    d632224b-b301-497d-b11e-558c7a994bf0: 'artikel categorie' # artikel categorie
    e1ff3449-bf98-4e59-a71b-827377851be1: 'klimaat artikels' # klimaat artikels
    e2dac4d6-69ac-4344-bcf4-75c81af47031: meldingen # meldingen
    e50cc673-9c06-4b69-90dc-9b2e7b6c70a7: 'bewerking1 bron' # bewerking1 bron
    e9597db3-8e0b-4d00-815b-4978d310ebde: 'bewerking2 titel' # bewerking2 titel
    eba72f32-6495-4b39-8d4a-2fe2627bd933: categories # categories
    fa58d604-e2d4-4f50-89ee-1da0ca242425: facebook # facebook
plugins:
  simple-text:
    edition: standard
    enabled: true
    schemaVersion: 1.0.2
  tinymce:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: solo
  live: true
  name: 2Check
  schemaVersion: 5.3.0.2
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
