defaultPlacement: end
enableVersioning: true
entryTypes:
  - 7b7e2a12-db70-497e-b18a-a7c30c5091a2 # carousel default
handle: carousel
maxAuthors: 2
name: carousel
previewTargets:
  1:
    __assoc__:
      -
        - label
        - primary
      -
        - urlFormat
        - /carousel/entry1/artikelCorrect.twig
      -
        - refresh
        - '1'
  2:
    __assoc__:
      -
        - label
        - second
      -
        - urlFormat
        - artikelFout.twig
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  72bbff78-21f3-4733-a195-230c2740ee45: # 2Check
    enabledByDefault: true
    hasUrls: true
    template: carousel/_entry
    uriFormat: 'carousel/{slug}'
type: channel
