defaultPlacement: end
enableVersioning: true
entryTypes:
  - a6dc8106-631a-4f64-92ba-ed7c809e459b # header home
handle: headerHome
maxAuthors: 1
name: 'header home'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  72bbff78-21f3-4733-a195-230c2740ee45: # 2Check
    enabledByDefault: true
    hasUrls: true
    template: header-home/_entry.twig
    uriFormat: header-home
type: single
