defaultPlacement: end
enableVersioning: true
entryTypes:
  - 5d01fce5-c081-46fe-9d61-6891b63888aa # logo
handle: logo
maxAuthors: 1
name: logo
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  72bbff78-21f3-4733-a195-230c2740ee45: # 2Check
    enabledByDefault: true
    hasUrls: true
    template: logo/_entry.twig
    uriFormat: logo
type: single
