defaultPlacement: end
enableVersioning: true
entryTypes:
  - b7ff6b30-2938-4468-b7a2-adc695db9827 # meldingen
handle: meldingen
maxAuthors: 1
name: meldingen
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  72bbff78-21f3-4733-a195-230c2740ee45: # 2Check
    enabledByDefault: true
    hasUrls: true
    template: meldingen/_entry.twig
    uriFormat: meldingen
type: single
