defaultPlacement: end
enableVersioning: true
entryTypes:
  - 953405b4-0756-4515-9553-38073cb87d35 # artikels nieuw
handle: nieuwArtikels
maxAuthors: 1
name: 'nieuw artikels'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  72bbff78-21f3-4733-a195-230c2740ee45: # 2Check
    enabledByDefault: true
    hasUrls: true
    template: nieuw-artikels/_entry.twig
    uriFormat: 'nieuw-artikels/{slug}'
type: channel
